/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic_Interface;

import Classes.DFA;
import Classes.FileManager;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;

/**
 *
 * @author Erick Contreras
 */
public class StartWindow extends javax.swing.JFrame {

    String root;
    File file;
    FileManager manager = new FileManager();
    DFA dfa = null;

    /**
     * Creates new form StartWindow
     */
    public StartWindow() {
        initComponents();
        jBtnValidation.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileRoot = new javax.swing.JTextField();
        jBtnGetFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAFile = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADFA = new javax.swing.JTextArea();
        jBtnCreateDFA = new javax.swing.JButton();
        jBtnValidation = new javax.swing.JButton();
        jBtnRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFileRoot.setEditable(false);

        jBtnGetFile.setText("Obtener archivo");
        jBtnGetFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGetFileActionPerformed(evt);
            }
        });

        jTAFile.setEditable(false);
        jTAFile.setColumns(10);
        jTAFile.setRows(10);
        jScrollPane1.setViewportView(jTAFile);

        jTADFA.setEditable(false);
        jTADFA.setColumns(10);
        jTADFA.setRows(10);
        jTADFA.setTabSize(5);
        jScrollPane2.setViewportView(jTADFA);

        jBtnCreateDFA.setText("Crear Automata"); // NOI18N
        jBtnCreateDFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCreateDFAActionPerformed(evt);
            }
        });

        jBtnValidation.setText("Crear validador");
        jBtnValidation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValidationActionPerformed(evt);
            }
        });

        jBtnRestart.setText("Reiniciar");
        jBtnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jFileRoot))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtnGetFile)
                            .addComponent(jBtnCreateDFA, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jBtnValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnRestart)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGetFile))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jBtnCreateDFA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBtnValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jBtnRestart)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGetFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGetFileActionPerformed
        // TODO add your handling code here:
        JFileChooser file_chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Texto", "txt");
        file_chooser.setFileFilter(filter);
        int valor = file_chooser.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            file = file_chooser.getSelectedFile();
            root = file.getPath();
            jFileRoot.setText(root);

            String[] text = manager.readAutomatonFile(root);
            if (text.length > 0) {
                String show_text = "";
                for (int i = 0; i < text.length; i++) {
                    show_text += text[i] + "\n";
                }
                jTAFile.setText(show_text);
            }
        }
    }//GEN-LAST:event_jBtnGetFileActionPerformed

    private void jBtnCreateDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCreateDFAActionPerformed
        // TODO add your handling code here:
        if (!jFileRoot.getText().equals("")) {
            dfa = new DFA(root);
            if (dfa.file.errors.isEmpty()) {
                jTADFA.setText(dfa.getDFA());
                jBtnValidation.setEnabled(true);

                JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
                compiler.run(null, null, null, "C:\\Users\\Erick Contreras\\Desktop\\URL\\2019\\"
                        + "5to Semestre\\Lenguajes\\LFA_Project\\ProyectoFase1_LFA\\src\\Classes\\AutomatonValidator.java");
            } else {
                jTADFA.setText(dfa.getPrintText());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un archivo primero");
        }
    }//GEN-LAST:event_jBtnCreateDFAActionPerformed

    private void jBtnValidationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValidationActionPerformed
        // TODO add your handling code here:
        String k = "";
        File x = new File("C:\\Users\\Erick Contreras\\Desktop\\URL\\2019\\5to Semestre\\Lenguajes\\LFA_Project\\ProyectoFase1_LFA\\dist\\ProyectoFase1_LFA.jar");
        try {
            Desktop.getDesktop().open(x);
            System.exit(0);
            
        } catch (IOException ex) {
            Logger.getLogger(StartWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnValidationActionPerformed

    private void jBtnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRestartActionPerformed
        // TODO add your handling code here:
        root = "";
        dfa = null;
        jFileRoot.setText("");
        jTADFA.setText("");
        jTAFile.setText("");
        jBtnValidation.setEnabled(false);

    }//GEN-LAST:event_jBtnRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCreateDFA;
    private javax.swing.JButton jBtnGetFile;
    private javax.swing.JButton jBtnRestart;
    private javax.swing.JButton jBtnValidation;
    private javax.swing.JTextField jFileRoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADFA;
    private javax.swing.JTextArea jTAFile;
    // End of variables declaration//GEN-END:variables
}
